[package]
name = "samplerate"
version = "0.1.0"
authors = ["prior"]
readme = "README.md"
categories = ["multimedia::audio"]
description = "A library based on libsamplerate for converting samplerates"
repository = "https://github.com/Prior99/rust-samplerate"
keywords = ["audio", "samplerate"]
license = "BSD-2-Clause"

[dependencies]
libsamplerate-sys = "0.1"

[dev-dependencies]
hound = "3.4"
